#!/usr/bin/env python3
"""
Concord — Visual Demo Builder
Run from repo root: python update_demo.py
Creates CLI, dashboard, real LLM, and findings store.
"""
from pathlib import Path

ROOT = Path(".")

def w(path, content):
    p = ROOT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content.lstrip("\n"), encoding="utf-8")
    print(f"  ✓  {path}")

print("\n  Building Concord CLI + Dashboard + LLM...\n")

# ═══════════════════════════════════════════════════
# 1. requirements/base.txt  — add typer, jinja2
# ═══════════════════════════════════════════════════
w("requirements/base.txt", """
fastapi>=0.111
uvicorn[standard]>=0.29
pydantic>=2.0
pyyaml>=6.0
httpx>=0.27
asyncpg>=0.29
redis>=5.0
python-dotenv>=1.0
typer[all]>=0.12
rich>=13.0
""")

# ═══════════════════════════════════════════════════
# 2. .env.example  — add LLM keys
# ═══════════════════════════════════════════════════
w(".env.example", """
# ── LLM Backend ───────────────────────────────────────────────
# Choose one: ollama (free local), openai, nvidia_nim
LLM_PROVIDER=ollama
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=llama3.2

# OpenAI (if LLM_PROVIDER=openai)
OPENAI_API_KEY=sk-...
OPENAI_MODEL=gpt-4o-mini

# NVIDIA NIM (if LLM_PROVIDER=nvidia_nim) — free tier available
NVIDIA_API_KEY=nvapi-...
NVIDIA_MODEL=meta/llama-3.1-8b-instruct

# ── Database ──────────────────────────────────────────────────
POSTGRES_URL=postgresql://concord:concord@localhost:5432/concord
REDIS_URL=redis://localhost:6379

# ── Webhook ───────────────────────────────────────────────────
WEBHOOK_SECRET=changeme

# ── Concord API URL (for CLI) ─────────────────────────────────
CONCORD_API_URL=http://localhost:8000

# ── Connector tokens ─────────────────────────────────────────
TERRASECURE_TOKEN=
TRIVY_TOKEN=
KAGENT_TOKEN=
HOLMESGPT_TOKEN=
""")

# ═══════════════════════════════════════════════════
# 3. core/orchestrator/llm.py  — real LLM calls
# ═══════════════════════════════════════════════════
w("core/orchestrator/llm.py", '''
"""
core/orchestrator/llm.py
Pluggable LLM backend.
Set LLM_PROVIDER=ollama | openai | nvidia_nim in .env
"""
import json
import logging
import os

import httpx

logger = logging.getLogger("concord.llm")

DEVOPS_SYSTEM = """You are a senior DevSecOps engineer reviewing a security finding.
Given the finding context, generate a concise JSON response with exactly these keys:
  root_cause    — 1-2 sentence technical explanation
  suggested_fix — specific, copy-paste-able fix (code or command)
Respond ONLY with valid JSON. No markdown fences."""


class LLMBackend:
    def __init__(self):
        self.provider = os.getenv("LLM_PROVIDER", "ollama")
        self.ollama_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
        self.ollama_model = os.getenv("OLLAMA_MODEL", "llama3.2")
        self.openai_model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
        self.nvidia_model = os.getenv("NVIDIA_MODEL", "meta/llama-3.1-8b-instruct")

    async def generate_analysis(self, finding_id: str, severity: str,
                                artifact: str, title: str,
                                description: str) -> dict:
        """Call the LLM and return {root_cause, suggested_fix}."""
        user = (
            f"Finding ID: {finding_id}\\n"
            f"Severity: {severity}\\n"
            f"Artifact: {artifact}\\n"
            f"Title: {title}\\n"
            f"Description: {description}"
        )
        try:
            raw = await self._call(DEVOPS_SYSTEM, user)
            data = json.loads(raw.strip())
            return {
                "root_cause": data.get("root_cause", "Analysis generated by LLM."),
                "suggested_fix": data.get("suggested_fix", "See full response."),
                "llm_provider": self.provider,
            }
        except Exception as exc:
            logger.warning("LLM call failed (%s): %s", self.provider, exc)
            return {"root_cause": None, "suggested_fix": None, "llm_provider": self.provider}

    async def _call(self, system: str, user: str) -> str:
        if self.provider == "openai":
            return await self._openai(system, user,
                                      "https://api.openai.com/v1",
                                      os.getenv("OPENAI_API_KEY", ""),
                                      self.openai_model)
        if self.provider == "nvidia_nim":
            return await self._openai(system, user,
                                      "https://integrate.api.nvidia.com/v1",
                                      os.getenv("NVIDIA_API_KEY", ""),
                                      self.nvidia_model)
        return await self._ollama(system, user)

    async def _openai(self, system: str, user: str,
                      base_url: str, api_key: str, model: str) -> str:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"{base_url}/chat/completions",
                headers={"Authorization": f"Bearer {api_key}",
                         "Content-Type": "application/json"},
                json={"model": model,
                      "messages": [{"role": "system", "content": system},
                                   {"role": "user", "content": user}],
                      "max_tokens": 500, "temperature": 0.2},
            )
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"]

    async def _ollama(self, system: str, user: str) -> str:
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                f"{self.ollama_url}/api/chat",
                json={"model": self.ollama_model, "stream": False,
                      "messages": [{"role": "system", "content": system},
                                   {"role": "user", "content": user}]},
            )
            resp.raise_for_status()
            return resp.json()["message"]["content"]
''')

# ═══════════════════════════════════════════════════
# 4. api/routes/findings.py  — in-memory store + API
# ═══════════════════════════════════════════════════
w("api/routes/findings.py", '''
"""
api/routes/findings.py
In-memory findings store + REST API.
Phase 1: replace _FindingsStore with PostgreSQL.
"""
import os
import threading
from datetime import datetime

from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/findings", tags=["findings"])


class _FindingsStore:
    """Thread-safe in-memory singleton. Replaced by PostgreSQL in Phase 1."""
    _instance = None
    _lock = threading.Lock()

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._data = []
        return cls._instance

    def add(self, finding_id: str, severity: str, artifact: str,
            repo: str, source: str, path: str, result: dict) -> None:
        with self._lock:
            self._data.insert(0, {
                "id": finding_id,
                "severity": severity,
                "artifact": artifact,
                "repo": repo,
                "source": source,
                "path": path,
                "agent": result.get("agent"),
                "result": result,
                "timestamp": datetime.utcnow().isoformat(),
            })
            self._data = self._data[:200]

    def all(self, limit: int = 50) -> list:
        with self._lock:
            return list(self._data[:limit])

    def get(self, finding_id: str) -> dict | None:
        with self._lock:
            return next((f for f in self._data if f["id"] == finding_id), None)

    def stats(self) -> dict:
        with self._lock:
            total = len(self._data)
            fast = sum(1 for f in self._data if f.get("path") == "fast_path")
            tiebreaks = sum(
                1 for f in self._data
                if f.get("result", {}).get("auto_resolved") is False
            )
            return {"total": total, "fast": fast,
                    "ai": total - fast, "tiebreaks": tiebreaks}


store = _FindingsStore()


@router.get("/")
async def list_findings(limit: int = 50):
    return {
        "findings": store.all(limit),
        "stats": store.stats(),
        "llm_provider": os.getenv("LLM_PROVIDER", "ollama"),
    }


@router.get("/{finding_id}")
async def get_finding(finding_id: str):
    f = store.get(finding_id)
    if not f:
        raise HTTPException(status_code=404, detail="Finding not found")
    return f
''')

# ═══════════════════════════════════════════════════
# 5. core/orchestrator/orchestrator.py  — use LLM + store
# ═══════════════════════════════════════════════════
w("core/orchestrator/orchestrator.py", '''
"""
core/orchestrator/orchestrator.py
Main orchestrator — triage → agents → arbitration → LLM → store.
"""
import logging
import os
from datetime import datetime

from core.arbitration.resolver import arbitrate
from core.mcp_runtime.audit import AuditEntry, AuditLog
from core.models.agent_response import AgentResponse, compute_confidence
from core.models.finding import Finding
from core.triage.gate import TriageGate
from core.triage.rules.dedup import DedupRule
from core.triage.rules.patterns import KnownPatternRule
from core.triage.rules.severity import LowSeverityRule

logger = logging.getLogger("concord.orchestrator")


class Orchestrator:
    def __init__(self):
        self.triage = TriageGate(rules=[
            LowSeverityRule(),
            KnownPatternRule(known_ids=set()),
            DedupRule(),
        ])
        self.audit = AuditLog()

    async def process(self, finding: Finding) -> dict:
        logger.info("=" * 60)
        logger.info("CONCORD  %s  severity=%s  artifact=%s",
                    finding.id, finding.severity, finding.artifact)

        # ── Step 1: Triage ────────────────────────────────────────
        needs_ai, reason = self.triage.evaluate(finding)

        if not needs_ai:
            logger.info("[TRIAGE]  FAST PATH — %s", reason)
            result = {"path": "fast_path", "reason": reason, "pr_comment": None}
            self._store(finding, result)
            self.audit.record(AuditEntry(
                finding_id=finding.id, path="fast_path",
                reason=reason, agent=None, timestamp=datetime.utcnow(),
            ))
            return result

        logger.info("[TRIAGE]  ESCALATE — %s", reason)

        # ── Step 2: Agents ────────────────────────────────────────
        responses = await self._run_agents(finding)
        if not responses:
            return {"path": "ai_path", "error": "no agent responses"}

        # ── Step 3: Arbitrate ─────────────────────────────────────
        winner, auto_resolved = arbitrate(responses)
        sorted_r = sorted(responses, key=lambda r: r.confidence_score, reverse=True)
        scores = " | ".join(f"{r.agent}={r.confidence_score:.4f}" for r in sorted_r)
        logger.info("[ARBITRATION]  %s", scores)

        if auto_resolved:
            gap = (sorted_r[0].confidence_score - sorted_r[1].confidence_score
                   if len(sorted_r) > 1 else 1.0)
            logger.info("[ARBITRATION]  AUTO-RESOLVED  %s wins (gap=%.4f)",
                        winner.agent, gap)
        else:
            gap = sorted_r[0].confidence_score - sorted_r[1].confidence_score
            logger.info("[ARBITRATION]  HUMAN TIEBREAK  gap=%.4f < 0.15", gap)

        # ── Step 4: LLM PR comment ────────────────────────────────
        pr_comment = await self._build_pr_comment(
            finding, sorted_r, auto_resolved, winner
        )

        # ── Step 5: Audit + store ─────────────────────────────────
        result = {
            "path": "ai_path",
            "agent": winner.agent,
            "score": winner.confidence_score,
            "auto_resolved": auto_resolved,
            "pr_comment": pr_comment,
        }
        self._store(finding, result)
        self.audit.record(AuditEntry(
            finding_id=finding.id, path="ai_path",
            reason="auto_resolved" if auto_resolved else "human_tiebreak",
            agent=winner.agent, timestamp=datetime.utcnow(),
        ))
        logger.info("[OUTPUT]  %s", "auto-resolved" if auto_resolved else "human tiebreak")
        return result

    # ── Helpers ───────────────────────────────────────────────────

    async def _run_agents(self, finding: Finding) -> list[AgentResponse]:
        from agents.cicd.agent import CICDAgent
        from agents.infra.agent import InfraAgent

        responses = []
        for domain, agent in [("infra", InfraAgent()), ("cicd", CICDAgent())]:
            try:
                resp = await agent.analyze(finding)
                resp.confidence_score = compute_confidence(domain, finding.severity)
                logger.info("[%s]  confidence=%.4f  %s",
                            domain.upper(), resp.confidence_score, resp.root_cause[:55])
                responses.append(resp)
            except NotImplementedError:
                logger.warning("[%s]  not implemented yet", domain.upper())
            except Exception as exc:
                logger.error("[%s]  error: %s", domain.upper(), exc)
        return responses

    async def _build_pr_comment(self, finding: Finding,
                                sorted_r: list[AgentResponse],
                                auto_resolved: bool,
                                winner: AgentResponse) -> str:
        """Use LLM if configured, otherwise use stub responses."""
        provider = os.getenv("LLM_PROVIDER", "ollama")
        use_llm = provider in ("openai", "nvidia_nim") or (
            provider == "ollama" and os.getenv("OLLAMA_BASE_URL")
        )

        if use_llm:
            try:
                from core.orchestrator.llm import LLMBackend
                llm = LLMBackend()
                analysis = await llm.generate_analysis(
                    finding_id=finding.id,
                    severity=finding.severity,
                    artifact=finding.artifact,
                    title=finding.title,
                    description=finding.description,
                )
                if analysis.get("root_cause"):
                    winner.root_cause = analysis["root_cause"]
                    winner.suggested_fix = analysis["suggested_fix"]
                    logger.info("[LLM]  %s analysis generated", provider)
            except Exception as exc:
                logger.warning("[LLM]  failed, using stub: %s", exc)

        if auto_resolved:
            return (
                f"**Concord** — auto-resolved\\n\\n"
                f"**Agent:** {winner.agent}  |  "
                f"**Confidence:** {winner.confidence_score:.4f}\\n\\n"
                f"**Root cause:** {winner.root_cause}\\n\\n"
                f"**Suggested fix:**\\n{winner.suggested_fix}\\n\\n"
                f"*Confidence gap ≥ 0.15. Audit trail written.*"
            )
        else:
            top, second = sorted_r[0], sorted_r[1]
            gap = top.confidence_score - second.confidence_score
            return (
                f"**Concord** — human tiebreak required\\n\\n"
                f"Confidence gap **{gap:.4f}** is below threshold 0.15.\\n\\n"
                f"**{top.agent} agent** (score {top.confidence_score:.4f})\\n"
                f"Root cause: {top.root_cause}\\n"
                f"Fix: {top.suggested_fix}\\n\\n"
                f"**{second.agent} agent** (score {second.confidence_score:.4f})\\n"
                f"Root cause: {second.root_cause}\\n"
                f"Fix: {second.suggested_fix}\\n\\n"
                f"Reply `/approve {top.agent}` or `/approve {second.agent}` to resolve."
            )

    def _store(self, finding: Finding, result: dict) -> None:
        try:
            from api.routes.findings import store
            store.add(
                finding_id=finding.id,
                severity=finding.severity,
                artifact=finding.artifact,
                repo=finding.repository,
                source=finding.source,
                path=result["path"],
                result=result,
            )
        except Exception:
            pass  # store is optional
''')

# ═══════════════════════════════════════════════════
# 6. api/main.py  — serve dashboard at /
# ═══════════════════════════════════════════════════
w("api/main.py", '''
"""Concord FastAPI application — serves dashboard + API."""
import pathlib

from fastapi import FastAPI
from fastapi.responses import HTMLResponse

from api.routes import audit, events, findings

app = FastAPI(
    title="Concord",
    description="AI DevSecOps Orchestration Platform",
    version="0.1.0",
)

app.include_router(events.router)
app.include_router(findings.router)
app.include_router(audit.router)

_DASHBOARD = pathlib.Path(__file__).parent / "templates" / "dashboard.html"


@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def dashboard():
    """Concord visual dashboard."""
    return HTMLResponse(content=_DASHBOARD.read_text(encoding="utf-8"))


@app.get("/health")
def health():
    return {"status": "ok", "service": "concord", "version": "0.1.0"}
''')

# ═══════════════════════════════════════════════════
# 7. api/templates/dashboard.html  — THE DASHBOARD
# ═══════════════════════════════════════════════════
w("api/templates/dashboard.html", r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Concord — AI DevSecOps Platform</title>
<style>
:root{
  --bg:#0D0D0F;--surface:#141417;--surface2:#1C1C22;--border:#2A2A32;
  --brand:#1C9C76;--text:#E4E3DF;--muted:#6B6A6F;
  --red:#EF4444;--orange:#F97316;--yellow:#EAB308;--green:#22C55E;
}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--text);
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  font-size:13px;height:100vh;display:flex;flex-direction:column;overflow:hidden}

/* ── Header ─────────────────────────────── */
.hdr{display:flex;align-items:center;justify-content:space-between;
  padding:0 20px;height:52px;border-bottom:1px solid var(--border);
  background:var(--surface);flex-shrink:0}
.logo{display:flex;align-items:center;gap:10px;font-weight:700;font-size:16px;color:#fff}
.pulse{width:9px;height:9px;border-radius:50%;background:var(--brand);
  animation:pulse 2s infinite}
@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}
.hdr-meta{display:flex;gap:8px;align-items:center}
.pill{background:var(--surface2);border:1px solid var(--border);border-radius:4px;
  padding:2px 9px;font-size:11px;color:var(--muted)}

/* ── Layout ─────────────────────────────── */
.layout{display:flex;flex:1;overflow:hidden}

/* ── Sidebar ────────────────────────────── */
.sidebar{width:224px;border-right:1px solid var(--border);padding:16px 12px;
  overflow-y:auto;flex-shrink:0;background:var(--surface)}
.sec-lbl{font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;
  color:var(--muted);margin-bottom:8px;margin-top:16px}
.sec-lbl:first-child{margin-top:0}

.agent{display:flex;flex-direction:column;padding:8px 10px;border-radius:6px;
  margin-bottom:4px;border:1px solid transparent}
.agent.on{background:rgba(28,156,118,.08);border-color:rgba(28,156,118,.2)}
.agent.off{opacity:.38}
.agent-name{display:flex;align-items:center;gap:7px;font-weight:600;font-size:12px}
.agent-sub{font-size:10px;color:var(--muted);margin-top:3px;margin-left:16px}
.dot{width:6px;height:6px;border-radius:50%;flex-shrink:0}
.dot-g{background:var(--green)}.dot-d{background:#3A3A42}

.stat{display:flex;justify-content:space-between;padding:4px 2px;font-size:12px}
.sv{font-weight:700;color:var(--brand)}

.demo-wrap{display:flex;flex-direction:column;gap:5px}
.btn{padding:7px 12px;border-radius:5px;font-size:11px;font-weight:600;
  cursor:pointer;border:none;width:100%;text-align:left;transition:opacity .15s}
.btn:hover{opacity:.82}.btn:disabled{opacity:.4;cursor:not-allowed}
.btn-brand{background:var(--brand);color:#fff}
.btn-ghost{background:var(--surface2);border:1px solid var(--border);color:var(--text)}

/* ── Main ───────────────────────────────── */
.main{flex:1;display:flex;overflow:hidden}

/* ── Findings list ──────────────────────── */
.f-panel{width:355px;border-right:1px solid var(--border);
  display:flex;flex-direction:column;flex-shrink:0}
.p-hdr{display:flex;align-items:center;justify-content:space-between;
  padding:11px 14px;border-bottom:1px solid var(--border);background:var(--surface)}
.p-title{font-size:10px;font-weight:700;letter-spacing:.08em;
  text-transform:uppercase;color:var(--muted)}
.live-dot{width:5px;height:5px;border-radius:50%;background:var(--brand);
  animation:pulse 2s infinite;display:inline-block}
.f-list{flex:1;overflow-y:auto;padding:6px}

.fi{padding:10px 12px;border-radius:6px;margin-bottom:3px;cursor:pointer;
  border:1px solid transparent;transition:all .12s}
.fi:hover{background:var(--surface2);border-color:var(--border)}
.fi.sel{background:rgba(28,156,118,.08);border-color:var(--brand)}
.fi-top{display:flex;align-items:center;gap:7px;margin-bottom:4px}
.fi-id{font-family:monospace;font-size:11px;font-weight:600;color:#fff;
  flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.fi-time{font-size:10px;color:var(--muted);white-space:nowrap}
.fi-meta{display:flex;gap:6px;align-items:center;font-size:11px;color:var(--muted)}

.sev{font-size:10px;font-weight:700;padding:1px 6px;border-radius:3px;white-space:nowrap}
.sev-CRITICAL{background:rgba(239,68,68,.15);color:#EF4444}
.sev-HIGH{background:rgba(249,115,22,.15);color:#F97316}
.sev-MEDIUM{background:rgba(234,179,8,.15);color:#EAB308}
.sev-LOW{background:rgba(34,197,94,.15);color:#22C55E}
.sev-INFORMATIONAL{background:rgba(107,107,111,.15);color:var(--muted)}

.pbadge{font-size:9px;padding:1px 5px;border-radius:3px;font-weight:700}
.pbadge-fast{background:rgba(107,107,111,.18);color:var(--muted)}
.pbadge-ai{background:rgba(28,156,118,.15);color:var(--brand)}

.empty{text-align:center;color:var(--muted);padding:48px 20px;
  font-size:12px;line-height:1.8}

/* ── Detail panel ───────────────────────── */
.d-panel{flex:1;display:flex;flex-direction:column;overflow:hidden}
.d-body{flex:1;overflow-y:auto;padding:20px}

.kv{display:grid;grid-template-columns:110px 1fr;gap:5px 12px;margin-bottom:20px}
.kk{color:var(--muted);font-size:11px}
.kv-v{font-size:12px;font-family:monospace}
.sec-h{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;
  color:var(--muted);margin-bottom:8px}
.comment-box{background:var(--surface2);border:1px solid var(--border);
  border-radius:6px;padding:14px;font-size:12px;line-height:1.75;
  white-space:pre-wrap;word-break:break-word;font-family:monospace}
.tag-auto{color:var(--green);font-weight:700}
.tag-human{color:var(--yellow);font-weight:700}
.tag-fast{color:var(--muted)}

::-webkit-scrollbar{width:4px}
::-webkit-scrollbar-track{background:transparent}
::-webkit-scrollbar-thumb{background:var(--border);border-radius:2px}

/* Toast */
.toast{position:fixed;bottom:20px;right:20px;background:var(--brand);color:#fff;
  padding:10px 16px;border-radius:6px;font-size:12px;font-weight:600;
  opacity:0;transition:opacity .3s;pointer-events:none;z-index:100}
.toast.show{opacity:1}
</style>
</head>
<body>

<header class="hdr">
  <div style="display:flex;align-items:center;gap:14px">
    <div class="logo"><div class="pulse"></div>Concord</div>
    <span style="color:var(--muted);font-size:12px">AI DevSecOps Orchestration Platform</span>
  </div>
  <div class="hdr-meta">
    <span class="pill" id="llm-pill">LLM: —</span>
    <span class="pill">v0.1.0</span>
    <span class="pill" id="status-pill"><span class="live-dot"></span> Connecting…</span>
  </div>
</header>

<div class="layout">

  <aside class="sidebar">
    <div class="sec-lbl">Agents</div>

    <div class="agent on">
      <div class="agent-name"><div class="dot dot-g"></div>Infra Agent</div>
      <div class="agent-sub">TerraSecure · 92.45% acc</div>
    </div>
    <div class="agent on">
      <div class="agent-name"><div class="dot dot-g"></div>CI/CD Agent</div>
      <div class="agent-sub">Trivy · Checkov</div>
    </div>
    <div class="agent off">
      <div class="agent-name"><div class="dot dot-d"></div>K8s Agent</div>
      <div class="agent-sub">kagent · Phase 2A</div>
    </div>
    <div class="agent off">
      <div class="agent-name"><div class="dot dot-d"></div>Observability</div>
      <div class="agent-sub">HolmesGPT · Phase 2B</div>
    </div>
    <div class="agent off">
      <div class="agent-name"><div class="dot dot-d"></div>Security Policy</div>
      <div class="agent-sub">OPA / Semgrep · Phase 3</div>
    </div>

    <div class="sec-lbl" style="margin-top:20px">Stats</div>
    <div class="stat"><span style="color:var(--muted)">Total</span><span class="sv" id="s-total">0</span></div>
    <div class="stat"><span style="color:var(--muted)">Fast path</span><span class="sv" id="s-fast">0</span></div>
    <div class="stat"><span style="color:var(--muted)">AI path</span><span class="sv" id="s-ai">0</span></div>
    <div class="stat"><span style="color:var(--muted)">Tiebreaks</span><span class="sv" id="s-tie">0</span></div>

    <div class="sec-lbl" style="margin-top:20px">Run Demo</div>
    <div class="demo-wrap">
      <button class="btn btn-brand" onclick="demo('CRITICAL')">▶ CRITICAL finding</button>
      <button class="btn btn-ghost" onclick="demo('HIGH')">▶ HIGH finding</button>
      <button class="btn btn-ghost" onclick="demo('MEDIUM')">▶ MEDIUM finding</button>
      <button class="btn btn-ghost" onclick="demo('LOW')">▶ LOW (fast path)</button>
    </div>
  </aside>

  <div class="main">
    <div class="f-panel">
      <div class="p-hdr">
        <span class="p-title">Findings</span>
        <span style="font-size:10px;color:var(--muted)"><span class="live-dot"></span> live</span>
      </div>
      <div class="f-list" id="f-list">
        <div class="empty">
          No findings yet.<br>
          Click a demo button on the left<br>
          or push to CRMS via webhook.
        </div>
      </div>
    </div>

    <div class="d-panel">
      <div class="p-hdr"><span class="p-title">Finding Detail</span></div>
      <div class="d-body" id="d-body">
        <div style="display:flex;flex-direction:column;align-items:center;
                    justify-content:center;height:100%;color:var(--muted);gap:10px">
          <div style="font-size:32px;opacity:.2">◎</div>
          <div>Select a finding to see details</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="toast" id="toast"></div>

<script>
let sel = null, findings = [];

const toast = (msg, ms=2500) => {
  const el = document.getElementById('toast');
  el.textContent = msg; el.classList.add('show');
  setTimeout(() => el.classList.remove('show'), ms);
};

const sevCls = s => 'sev-' + (s||'LOW').toUpperCase();
const pathCls = p => p === 'ai_path' ? 'pbadge pbadge-ai' : 'pbadge pbadge-fast';
const pathLbl = p => p === 'ai_path' ? 'AI' : 'fast';

function ago(ts) {
  if (!ts) return '';
  const d = (Date.now() - new Date(ts+'Z').getTime()) / 1000;
  if (d < 60) return Math.round(d)+'s';
  if (d < 3600) return Math.round(d/60)+'m';
  return Math.round(d/3600)+'h';
}

function renderList(list) {
  const el = document.getElementById('f-list');
  if (!list.length) {
    el.innerHTML = '<div class="empty">No findings yet.<br>Click a demo button on the left<br>or push to CRMS via webhook.</div>';
    return;
  }
  el.innerHTML = list.map(f => `
    <div class="fi ${f.id===sel?'sel':''}" onclick="pick('${f.id}')">
      <div class="fi-top">
        <span class="sev ${sevCls(f.severity)}">${f.severity}</span>
        <span class="fi-id">${f.id}</span>
        <span class="fi-time">${ago(f.timestamp)}</span>
      </div>
      <div class="fi-meta">
        <span class="${pathCls(f.path)}">${pathLbl(f.path)}</span>
        <span>${(f.artifact||'').split('/').pop()}</span>
        <span style="margin-left:auto">${f.repo||''}</span>
      </div>
    </div>`).join('');
}

function pick(id) {
  sel = id;
  const f = findings.find(x => x.id === id);
  if (!f) return;
  renderList(findings);
  const r = f.result || {};
  const isAI = r.path === 'ai_path';
  const resCls = r.auto_resolved === true  ? 'tag-auto'
               : r.auto_resolved === false ? 'tag-human'
               : 'tag-fast';
  const resLbl = r.auto_resolved === true  ? '✓ Auto-resolved'
               : r.auto_resolved === false ? '⚡ Human tiebreak'
               : '⚡ Fast path';
  const comment = (r.pr_comment || '').replace(/\\n/g, '\n');
  document.getElementById('d-body').innerHTML = `
    <div class="sec-h">Finding</div>
    <div class="kv">
      <span class="kk">ID</span><span class="kv-v">${f.id}</span>
      <span class="kk">Severity</span><span><span class="sev ${sevCls(f.severity)}">${f.severity}</span></span>
      <span class="kk">Artifact</span><span class="kv-v">${f.artifact||'—'}</span>
      <span class="kk">Repository</span><span class="kv-v">${f.repo||'—'}</span>
      <span class="kk">Source</span><span class="kv-v">${f.source||'—'}</span>
    </div>
    <div class="sec-h">Concord Analysis</div>
    <div class="kv">
      <span class="kk">Path</span><span class="kv-v">${r.path||'—'}</span>
      ${isAI ? `
      <span class="kk">Agent</span><span class="kv-v">${r.agent||'—'}</span>
      <span class="kk">Confidence</span><span class="kv-v">${r.score!=null?r.score.toFixed(4):'—'}</span>` : ''}
      <span class="kk">Resolution</span><span class="${resCls}">${resLbl}</span>
    </div>
    ${comment ? `<div class="sec-h" style="margin-top:16px">PR Comment</div>
    <div class="comment-box">${comment}</div>` : ''}`;
}

async function demo(sev) {
  const btns = document.querySelectorAll('.btn');
  btns.forEach(b => b.disabled = true);
  toast(`Running ${sev} finding through Concord…`);
  try {
    const r = await fetch('/events/demo?severity='+sev, {method:'POST'});
    const data = await r.json();
    const msg = data.path === 'fast_path'
      ? `Fast path — no LLM (${sev})`
      : `Done — ${data.auto_resolved ? 'auto-resolved' : 'human tiebreak'}`;
    toast(msg);
    await refresh();
    if (findings.length) pick(findings[0].id);
  } catch(e) { toast('Error: '+e.message, 4000); }
  finally { btns.forEach(b => b.disabled = false); }
}

async function refresh() {
  try {
    const r = await fetch('/findings/');
    const d = await r.json();
    findings = d.findings || [];
    document.getElementById('s-total').textContent = d.stats?.total || 0;
    document.getElementById('s-fast').textContent  = d.stats?.fast  || 0;
    document.getElementById('s-ai').textContent    = d.stats?.ai    || 0;
    document.getElementById('s-tie').textContent   = d.stats?.tiebreaks || 0;
    document.getElementById('llm-pill').textContent = 'LLM: ' + (d.llm_provider || 'ollama');
    document.getElementById('status-pill').innerHTML =
      '<span class="live-dot"></span> Running';
    renderList(findings);
    if (sel) pick(sel);
  } catch(e) {
    document.getElementById('status-pill').textContent = '● Offline';
  }
}

setInterval(refresh, 2000);
refresh();
</script>
</body>
</html>
""")

# ═══════════════════════════════════════════════════
# 8. concord_cli/main.py  — Typer CLI
# ═══════════════════════════════════════════════════
w("concord_cli/__init__.py", "")

w("concord_cli/main.py", r'''
#!/usr/bin/env python3
"""
Concord CLI — kagent-style command-line interface.
Usage (from repo root):
    python concord_cli/main.py [COMMAND] [OPTIONS]
    python concord_cli/main.py --help
"""
import asyncio
import os
import sys
import webbrowser

import httpx
import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

app = typer.Typer(
    name="concord",
    help="Concord — AI DevSecOps Orchestration Platform  |  github.com/BeyondBug/Concord",
    add_completion=False,
    rich_markup_mode="rich",
)
con = Console()
API = os.getenv("CONCORD_API_URL", "http://localhost:8000")

SEV_COLOR = {
    "CRITICAL": "red", "HIGH": "orange3",
    "MEDIUM": "yellow", "LOW": "green",
}


@app.command()
def version():
    """Print version information."""
    con.print("[bold green]Concord[/bold green] v0.1.0")
    con.print("  AI DevSecOps Orchestration Platform")
    con.print("  github.com/BeyondBug/Concord")
    con.print(f"  API: {API}")


@app.command()
def agents():
    """List all domain agents and their current status."""
    t = Table(title="Domain Agents", header_style="bold green", show_lines=False)
    t.add_column("#",  style="dim", width=3)
    t.add_column("Agent",        style="bold")
    t.add_column("Backing Tool", style="cyan")
    t.add_column("Reliability",  justify="right")
    t.add_column("Status",       justify="center")
    t.add_column("Phase",        style="dim")

    AGENTS = [
        ("0", "infra",        "TerraSecure (ML 92.45%)",  "0.92", "[green]● Active[/green]",  "0 → 2A"),
        ("1", "cicd",         "Trivy · Checkov",           "0.88", "[green]● Active[/green]",  "0 → 2B"),
        ("2", "kubernetes",   "kagent (Apache 2.0)",       "0.82", "[dim]○ Planned[/dim]",     "2A"),
        ("3", "observability","HolmesGPT (MIT)",           "0.80", "[dim]○ Planned[/dim]",     "2B"),
        ("4", "security",     "OPA / Semgrep",             "0.85", "[dim]○ Planned[/dim]",     "3"),
    ]
    for row in AGENTS:
        t.add_row(*row)
    con.print(t)


@app.command()
def invoke(
    severity: str = typer.Option("CRITICAL", "--severity", "-s",
                                  help="CRITICAL | HIGH | MEDIUM | LOW"),
    finding_id: str = typer.Option("CVE-2024-33663", "--id"),
    repo: str = typer.Option("BeyondBug/CRMS", "--repo"),
):
    """Invoke Concord on a finding and show the full pipeline result."""
    c = SEV_COLOR.get(severity.upper(), "white")
    con.print(Panel(
        f"[bold]ID:[/bold] {finding_id}  "
        f"[bold]Severity:[/bold] [{c}]{severity.upper()}[/{c}]  "
        f"[bold]Repo:[/bold] {repo}",
        title="[bold green]▶ Concord Invoke[/bold green]",
        border_style="green",
    ))

    try:
        with httpx.Client(timeout=30) as client:
            r = client.post(f"{API}/events/demo",
                            params={"severity": severity.upper()})
            r.raise_for_status()
            _print_result(r.json())
    except httpx.ConnectError:
        con.print("[yellow]  API not running — standalone mode...[/yellow]")
        asyncio.run(_standalone(severity, finding_id, repo))


def _print_result(result: dict):
    path = result.get("path", "unknown")
    if path == "fast_path":
        con.print(f"\n  [bold cyan]TRIAGE[/bold cyan]  FAST PATH — {result.get('reason')}")
        con.print("  [dim]No LLM call made. Zero inference cost.[/dim]")
    else:
        agent = result.get("agent", "unknown")
        score = result.get("score", 0)
        res = result.get("auto_resolved")
        con.print(f"\n  [bold cyan]TRIAGE[/bold cyan]      ESCALATED")
        con.print(f"  [bold cyan]AGENT[/bold cyan]       {agent}  (confidence {score:.4f})")
        if res:
            con.print("  [bold cyan]ARBITRATION[/bold cyan] [green]AUTO-RESOLVED[/green] — gap ≥ 0.15")
        else:
            con.print("  [bold cyan]ARBITRATION[/bold cyan] [yellow]HUMAN TIEBREAK[/yellow] — gap < 0.15")
        if result.get("pr_comment"):
            con.print()
            con.print(Panel(
                result["pr_comment"].replace("\\n", "\n"),
                title="[bold]PR Comment[/bold]",
                border_style="cyan",
            ))
    con.print()


async def _standalone(severity, finding_id, repo):
    from core.models.finding import Finding
    from core.orchestrator.orchestrator import Orchestrator
    f = Finding(
        id=finding_id, source="concord-cli",
        artifact="infra/terraform/main.tf",
        severity=severity.upper(),
        title="IAM policy allows overly permissive actions",
        description="Invoked via concord CLI (standalone)",
        raw={}, repository=repo,
    )
    result = await Orchestrator().process(f)
    _print_result(result)


@app.command()
def findings(limit: int = typer.Option(10, "--limit", "-n")):
    """Show recent findings from the live API."""
    try:
        with httpx.Client(timeout=10) as client:
            r = client.get(f"{API}/findings/", params={"limit": limit})
            r.raise_for_status()
            d = r.json()
    except Exception as e:
        con.print(f"[red]Cannot reach API ({API}): {e}[/red]")
        con.print("  Start with: [bold]uvicorn api.main:app --reload[/bold]")
        raise typer.Exit(1)

    s = d.get("stats", {})
    con.print(
        f"\n  Total [bold]{s.get('total',0)}[/bold]  "
        f"Fast [green]{s.get('fast',0)}[/green]  "
        f"AI [cyan]{s.get('ai',0)}[/cyan]  "
        f"Tiebreaks [yellow]{s.get('tiebreaks',0)}[/yellow]"
    )
    lst = d.get("findings", [])
    if not lst:
        con.print("\n  [dim]No findings yet. Run: concord invoke[/dim]")
        return

    t = Table(show_header=True, header_style="bold", show_lines=False)
    t.add_column("ID",         style="dim", no_wrap=True, max_width=18)
    t.add_column("Severity")
    t.add_column("Path")
    t.add_column("Agent")
    t.add_column("Artifact",   style="dim")
    t.add_column("Age",        style="dim")

    import time
    for f in lst:
        sev = f.get("severity", "")
        c = SEV_COLOR.get(sev, "white")
        path = f.get("path", "")
        path_str = f"[cyan]{path}[/cyan]" if "ai" in path else f"[dim]{path}[/dim]"
        t.add_row(
            f.get("id","")[:17], f"[{c}]{sev}[/{c}]", path_str,
            f.get("agent","—"), (f.get("artifact","") or "").split("/")[-1],
            f.get("timestamp","")[:10],
        )
    con.print(t)


@app.command()
def dashboard():
    """Open the Concord dashboard in your default browser."""
    url = API
    con.print(f"\n  Opening dashboard → [bold cyan]{url}[/bold cyan]")
    con.print("  Make sure API is running: [bold]uvicorn api.main:app --reload[/bold]\n")
    webbrowser.open(url)


@app.command()
def get(resource: str = typer.Argument(..., help="agents | findings | stats")):
    """Get a Concord resource (like kagent get agent)."""
    if resource == "agents":
        agents()
    elif resource in ("findings", "finding"):
        findings()
    else:
        con.print(f"[red]Unknown resource: {resource}[/red]")
        con.print("Available: agents, findings")


if __name__ == "__main__":
    app()
''')

print("\n  ✓  All files created.\n")
print("  Run in order:")
print()
print("  1. pip install typer rich httpx            (new deps)")
print("  2. uvicorn api.main:app --reload           (start API)")
print("  3. open http://localhost:8000              (dashboard)")
print("  4. python concord_cli/main.py agents       (CLI)")
print("  5. python concord_cli/main.py invoke       (live demo)")
print()