"""
core/github_utils.py
Creates a real GitHub issue on the scanned repo using the GitHub REST API.
Requires GITHUB_TOKEN in .env
"""
import logging
import os

logger = logging.getLogger("concord.github")


def create_issue(repo: str, title: str, body: str,
                 labels: list[str] | None = None) -> dict | None:
    """
    Create a GitHub issue on `repo` (e.g. "crms-devops/crms").
    Returns the created issue dict or None on failure.
    Requires env var: GITHUB_TOKEN
    """
    import httpx

    token = os.getenv("GITHUB_TOKEN", "")
    if not token:
        logger.warning("GITHUB_TOKEN not set — skipping GitHub issue creation")
        return None

    url = f"https://api.github.com/repos/{repo}/issues"
    payload: dict = {"title": title, "body": body}
    if labels:
        payload["labels"] = labels

    try:
        r = httpx.post(
            url,
            headers={
                "Authorization": f"token {token}",
                "Accept": "application/vnd.github.v3+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            json=payload,
            timeout=15,
        )
        r.raise_for_status()
        data = r.json()
        logger.info("GitHub issue created: %s", data.get("html_url"))
        return data
    except Exception as exc:
        logger.error("GitHub issue creation failed: %s", exc)
        return None


def format_issue_body(finding_id: str, severity: str, repo: str,
                      infra: dict, cicd: dict,
                      pr_comment: str, agent: str, score: float,
                      auto_resolved: bool) -> str:
    """Format a rich GitHub issue body from Checkov findings."""
    resolution = "Auto-resolved" if auto_resolved else "⚡ Human tiebreak required"
    gap_note = ("" if auto_resolved
                else "\n\n> Two agents disagree. Please review and `/approve` one agent.")

    return f"""## Concord Security Report — {repo}

**Finding ID:** `{finding_id}`
**Severity:** {severity}
**Winning Agent:** {agent} (confidence `{score:.4f}`)
**Resolution:** {resolution}{gap_note}

---

### Infrastructure Findings (Terraform) — {infra["total"]} violation(s)

```
{infra["root_cause"]}
```

**Fix:**
```
{infra["fix"]}
```

---

### CI/CD Findings (Kubernetes/Docker) — {cicd["total"]} violation(s)

```
{cicd["root_cause"]}
```

**Fix:**
```
{cicd["fix"]}
```

---

### Concord PR Comment

{pr_comment}

---

*Generated by [Concord](https://github.com/BeyondBug/Concord) — AI DevSecOps Orchestration Platform*
"""
