"""
core/orchestrator/llm.py
Pluggable LLM backend.
Set LLM_PROVIDER=ollama | openai | nvidia_nim in .env
"""
import json
import logging
import os

import httpx

logger = logging.getLogger("concord.llm")

DEVOPS_SYSTEM = """You are a senior DevSecOps engineer reviewing a security finding.
Given the finding context, generate a concise JSON response with exactly these keys:
  root_cause    — 1-2 sentence technical explanation
  suggested_fix — specific, copy-paste-able fix (code or command)
Respond ONLY with valid JSON. No markdown fences."""


class LLMBackend:
    def __init__(self):
        self.provider = os.getenv("LLM_PROVIDER", "ollama")
        self.ollama_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
        self.ollama_model = os.getenv("OLLAMA_MODEL", "llama3.2")
        self.openai_model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
        self.nvidia_model = os.getenv("NVIDIA_MODEL", "meta/llama-3.1-8b-instruct")

    async def generate_analysis(self, finding_id: str, severity: str,
                                artifact: str, title: str,
                                description: str) -> dict:
        """Call the LLM and return {root_cause, suggested_fix}."""
        user = (
            f"Finding ID: {finding_id}\n"
            f"Severity: {severity}\n"
            f"Artifact: {artifact}\n"
            f"Title: {title}\n"
            f"Description: {description}"
        )
        try:
            raw = await self._call(DEVOPS_SYSTEM, user)
            data = json.loads(raw.strip())
            return {
                "root_cause": data.get("root_cause", "Analysis generated by LLM."),
                "suggested_fix": data.get("suggested_fix", "See full response."),
                "llm_provider": self.provider,
            }
        except Exception as exc:
            logger.warning("LLM call failed (%s): %s", self.provider, exc)
            return {"root_cause": None, "suggested_fix": None, "llm_provider": self.provider}

    async def _call(self, system: str, user: str) -> str:
        if self.provider == "openai":
            return await self._openai(system, user,
                                      "https://api.openai.com/v1",
                                      os.getenv("OPENAI_API_KEY", ""),
                                      self.openai_model)
        if self.provider == "nvidia_nim":
            return await self._openai(system, user,
                                      "https://integrate.api.nvidia.com/v1",
                                      os.getenv("NVIDIA_API_KEY", ""),
                                      self.nvidia_model)
        return await self._ollama(system, user)

    async def _openai(self, system: str, user: str,
                      base_url: str, api_key: str, model: str) -> str:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"{base_url}/chat/completions",
                headers={"Authorization": f"Bearer {api_key}",
                         "Content-Type": "application/json"},
                json={"model": model,
                      "messages": [{"role": "system", "content": system},
                                   {"role": "user", "content": user}],
                      "max_tokens": 500, "temperature": 0.2},
            )
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"]

    async def _ollama(self, system: str, user: str) -> str:
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                f"{self.ollama_url}/api/chat",
                json={"model": self.ollama_model, "stream": False,
                      "messages": [{"role": "system", "content": system},
                                   {"role": "user", "content": user}]},
            )
            resp.raise_for_status()
            return resp.json()["message"]["content"]
